/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthLayoutRouteImport } from './routes/_auth-layout'
import { Route as AuthLayoutActivityRouteImport } from './routes/_auth-layout/activity'
import { Route as AuthLayoutDashboardRouteImport } from './routes/_auth-layout/dashboard'
import { Route as AuthLayoutSettingRouteImport } from './routes/_auth-layout/setting'
import { Route as AuthLayoutTeamRouteImport } from './routes/_auth-layout/team'
import { Route as AuthLayoutClientsIndexRouteImport } from './routes/_auth-layout/clients/index'
import { Route as AuthLayoutInvoicesIndexRouteImport } from './routes/_auth-layout/invoices/index'
import { Route as AuthLayoutInvoicesIdRouteImport } from './routes/_auth-layout/invoices/$id'
import { Route as AuthLayoutInvoicesNewRouteImport } from './routes/_auth-layout/invoices/new'
import { Route as AuthLayoutMemosIndexRouteImport } from './routes/_auth-layout/memos/index'
import { Route as AuthLayoutProductsIndexRouteImport } from './routes/_auth-layout/products/index'
import { Route as AuthLayoutSettingsIndexRouteImport } from './routes/_auth-layout/settings/index'
import { Route as AuthLayoutSettingsBanksRouteImport } from './routes/_auth-layout/settings/banks'
import { Route as AuthLayoutSettingsBusinessesRouteImport } from './routes/_auth-layout/settings/businesses'
import { Route as AuthLayoutSettingsCompaniesRouteImport } from './routes/_auth-layout/settings/companies'
import { Route as AuthLayoutSettingsFxRatesRouteImport } from './routes/_auth-layout/settings/fx-rates'
import { Route as AuthLayoutSettingsOrganizationRouteImport } from './routes/_auth-layout/settings/organization'
import { Route as AuthLayoutSettingsProfileRouteImport } from './routes/_auth-layout/settings/profile'
import { Route as AuthAuthAcceptInvitationRouteImport } from './routes/_auth/auth/accept-invitation'
import { Route as AuthAuthForgotPasswordRouteImport } from './routes/_auth/auth/forgot-password'
import { Route as AuthAuthLoginRouteImport } from './routes/_auth/auth/login'
import { Route as AuthAuthResetPasswordRouteImport } from './routes/_auth/auth/reset-password'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronFxRatesRouteImport } from './routes/api/cron/fx-rates'
import { Route as AuthLayoutInvoicesIdEditRouteImport } from './routes/_auth-layout/invoices/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRoute = AuthLayoutRouteImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutActivityRoute = AuthLayoutActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutDashboardRoute = AuthLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSettingRoute = AuthLayoutSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutTeamRoute = AuthLayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutClientsIndexRoute = AuthLayoutClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutInvoicesIndexRoute = AuthLayoutInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutInvoicesIdRoute = AuthLayoutInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutInvoicesNewRoute = AuthLayoutInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutMemosIndexRoute = AuthLayoutMemosIndexRouteImport.update({
  id: '/memos/',
  path: '/memos/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutProductsIndexRoute = AuthLayoutProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSettingsIndexRoute = AuthLayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSettingsBanksRoute = AuthLayoutSettingsBanksRouteImport.update({
  id: '/settings/banks',
  path: '/settings/banks',
  getParentRoute: () => AuthLayoutRoute,
} as any)
const AuthLayoutSettingsBusinessesRoute =
  AuthLayoutSettingsBusinessesRouteImport.update({
    id: '/settings/businesses',
    path: '/settings/businesses',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutSettingsCompaniesRoute =
  AuthLayoutSettingsCompaniesRouteImport.update({
    id: '/settings/companies',
    path: '/settings/companies',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutSettingsFxRatesRoute =
  AuthLayoutSettingsFxRatesRouteImport.update({
    id: '/settings/fx-rates',
    path: '/settings/fx-rates',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutSettingsOrganizationRoute =
  AuthLayoutSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthLayoutSettingsProfileRoute =
  AuthLayoutSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthLayoutRoute,
  } as any)
const AuthAuthAcceptInvitationRoute =
  AuthAuthAcceptInvitationRouteImport.update({
    id: '/auth/accept-invitation',
    path: '/auth/accept-invitation',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthAuthForgotPasswordRoute = AuthAuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthResetPasswordRoute = AuthAuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronFxRatesRoute = ApiCronFxRatesRouteImport.update({
  id: '/api/cron/fx-rates',
  path: '/api/cron/fx-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutInvoicesIdEditRoute =
  AuthLayoutInvoicesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthLayoutInvoicesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof AuthLayoutActivityRoute
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/setting': typeof AuthLayoutSettingRoute
  '/team': typeof AuthLayoutTeamRoute
  '/invoices/$id': typeof AuthLayoutInvoicesIdRouteWithChildren
  '/invoices/new': typeof AuthLayoutInvoicesNewRoute
  '/settings/banks': typeof AuthLayoutSettingsBanksRoute
  '/settings/businesses': typeof AuthLayoutSettingsBusinessesRoute
  '/settings/companies': typeof AuthLayoutSettingsCompaniesRoute
  '/settings/fx-rates': typeof AuthLayoutSettingsFxRatesRoute
  '/settings/organization': typeof AuthLayoutSettingsOrganizationRoute
  '/settings/profile': typeof AuthLayoutSettingsProfileRoute
  '/auth/accept-invitation': typeof AuthAuthAcceptInvitationRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/fx-rates': typeof ApiCronFxRatesRoute
  '/clients/': typeof AuthLayoutClientsIndexRoute
  '/invoices/': typeof AuthLayoutInvoicesIndexRoute
  '/memos/': typeof AuthLayoutMemosIndexRoute
  '/products/': typeof AuthLayoutProductsIndexRoute
  '/settings/': typeof AuthLayoutSettingsIndexRoute
  '/invoices/$id/edit': typeof AuthLayoutInvoicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof AuthLayoutActivityRoute
  '/dashboard': typeof AuthLayoutDashboardRoute
  '/setting': typeof AuthLayoutSettingRoute
  '/team': typeof AuthLayoutTeamRoute
  '/invoices/$id': typeof AuthLayoutInvoicesIdRouteWithChildren
  '/invoices/new': typeof AuthLayoutInvoicesNewRoute
  '/settings/banks': typeof AuthLayoutSettingsBanksRoute
  '/settings/businesses': typeof AuthLayoutSettingsBusinessesRoute
  '/settings/companies': typeof AuthLayoutSettingsCompaniesRoute
  '/settings/fx-rates': typeof AuthLayoutSettingsFxRatesRoute
  '/settings/organization': typeof AuthLayoutSettingsOrganizationRoute
  '/settings/profile': typeof AuthLayoutSettingsProfileRoute
  '/auth/accept-invitation': typeof AuthAuthAcceptInvitationRoute
  '/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/fx-rates': typeof ApiCronFxRatesRoute
  '/clients': typeof AuthLayoutClientsIndexRoute
  '/invoices': typeof AuthLayoutInvoicesIndexRoute
  '/memos': typeof AuthLayoutMemosIndexRoute
  '/products': typeof AuthLayoutProductsIndexRoute
  '/settings': typeof AuthLayoutSettingsIndexRoute
  '/invoices/$id/edit': typeof AuthLayoutInvoicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth-layout': typeof AuthLayoutRouteWithChildren
  '/_auth-layout/activity': typeof AuthLayoutActivityRoute
  '/_auth-layout/dashboard': typeof AuthLayoutDashboardRoute
  '/_auth-layout/setting': typeof AuthLayoutSettingRoute
  '/_auth-layout/team': typeof AuthLayoutTeamRoute
  '/_auth-layout/invoices/$id': typeof AuthLayoutInvoicesIdRouteWithChildren
  '/_auth-layout/invoices/new': typeof AuthLayoutInvoicesNewRoute
  '/_auth-layout/settings/banks': typeof AuthLayoutSettingsBanksRoute
  '/_auth-layout/settings/businesses': typeof AuthLayoutSettingsBusinessesRoute
  '/_auth-layout/settings/companies': typeof AuthLayoutSettingsCompaniesRoute
  '/_auth-layout/settings/fx-rates': typeof AuthLayoutSettingsFxRatesRoute
  '/_auth-layout/settings/organization': typeof AuthLayoutSettingsOrganizationRoute
  '/_auth-layout/settings/profile': typeof AuthLayoutSettingsProfileRoute
  '/_auth/auth/accept-invitation': typeof AuthAuthAcceptInvitationRoute
  '/_auth/auth/forgot-password': typeof AuthAuthForgotPasswordRoute
  '/_auth/auth/login': typeof AuthAuthLoginRoute
  '/_auth/auth/reset-password': typeof AuthAuthResetPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/fx-rates': typeof ApiCronFxRatesRoute
  '/_auth-layout/clients/': typeof AuthLayoutClientsIndexRoute
  '/_auth-layout/invoices/': typeof AuthLayoutInvoicesIndexRoute
  '/_auth-layout/memos/': typeof AuthLayoutMemosIndexRoute
  '/_auth-layout/products/': typeof AuthLayoutProductsIndexRoute
  '/_auth-layout/settings/': typeof AuthLayoutSettingsIndexRoute
  '/_auth-layout/invoices/$id/edit': typeof AuthLayoutInvoicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/setting'
    | '/team'
    | '/invoices/$id'
    | '/invoices/new'
    | '/settings/banks'
    | '/settings/businesses'
    | '/settings/companies'
    | '/settings/fx-rates'
    | '/settings/organization'
    | '/settings/profile'
    | '/auth/accept-invitation'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/api/auth/$'
    | '/api/cron/fx-rates'
    | '/clients/'
    | '/invoices/'
    | '/memos/'
    | '/products/'
    | '/settings/'
    | '/invoices/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/setting'
    | '/team'
    | '/invoices/$id'
    | '/invoices/new'
    | '/settings/banks'
    | '/settings/businesses'
    | '/settings/companies'
    | '/settings/fx-rates'
    | '/settings/organization'
    | '/settings/profile'
    | '/auth/accept-invitation'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/api/auth/$'
    | '/api/cron/fx-rates'
    | '/clients'
    | '/invoices'
    | '/memos'
    | '/products'
    | '/settings'
    | '/invoices/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth-layout'
    | '/_auth-layout/activity'
    | '/_auth-layout/dashboard'
    | '/_auth-layout/setting'
    | '/_auth-layout/team'
    | '/_auth-layout/invoices/$id'
    | '/_auth-layout/invoices/new'
    | '/_auth-layout/settings/banks'
    | '/_auth-layout/settings/businesses'
    | '/_auth-layout/settings/companies'
    | '/_auth-layout/settings/fx-rates'
    | '/_auth-layout/settings/organization'
    | '/_auth-layout/settings/profile'
    | '/_auth/auth/accept-invitation'
    | '/_auth/auth/forgot-password'
    | '/_auth/auth/login'
    | '/_auth/auth/reset-password'
    | '/api/auth/$'
    | '/api/cron/fx-rates'
    | '/_auth-layout/clients/'
    | '/_auth-layout/invoices/'
    | '/_auth-layout/memos/'
    | '/_auth-layout/products/'
    | '/_auth-layout/settings/'
    | '/_auth-layout/invoices/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronFxRatesRoute: typeof ApiCronFxRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout': {
      id: '/_auth-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout/activity': {
      id: '/_auth-layout/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthLayoutActivityRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/dashboard': {
      id: '/_auth-layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthLayoutDashboardRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/setting': {
      id: '/_auth-layout/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof AuthLayoutSettingRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/team': {
      id: '/_auth-layout/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthLayoutTeamRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/clients/': {
      id: '/_auth-layout/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthLayoutClientsIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/invoices/': {
      id: '/_auth-layout/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthLayoutInvoicesIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/invoices/$id': {
      id: '/_auth-layout/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthLayoutInvoicesIdRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/invoices/new': {
      id: '/_auth-layout/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthLayoutInvoicesNewRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/memos/': {
      id: '/_auth-layout/memos/'
      path: '/memos'
      fullPath: '/memos/'
      preLoaderRoute: typeof AuthLayoutMemosIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/products/': {
      id: '/_auth-layout/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthLayoutProductsIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/settings/': {
      id: '/_auth-layout/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthLayoutSettingsIndexRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/settings/banks': {
      id: '/_auth-layout/settings/banks'
      path: '/settings/banks'
      fullPath: '/settings/banks'
      preLoaderRoute: typeof AuthLayoutSettingsBanksRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/settings/businesses': {
      id: '/_auth-layout/settings/businesses'
      path: '/settings/businesses'
      fullPath: '/settings/businesses'
      preLoaderRoute: typeof AuthLayoutSettingsBusinessesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/settings/companies': {
      id: '/_auth-layout/settings/companies'
      path: '/settings/companies'
      fullPath: '/settings/companies'
      preLoaderRoute: typeof AuthLayoutSettingsCompaniesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/settings/fx-rates': {
      id: '/_auth-layout/settings/fx-rates'
      path: '/settings/fx-rates'
      fullPath: '/settings/fx-rates'
      preLoaderRoute: typeof AuthLayoutSettingsFxRatesRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/settings/organization': {
      id: '/_auth-layout/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthLayoutSettingsOrganizationRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth-layout/settings/profile': {
      id: '/_auth-layout/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthLayoutSettingsProfileRouteImport
      parentRoute: typeof AuthLayoutRoute
    }
    '/_auth/auth/accept-invitation': {
      id: '/_auth/auth/accept-invitation'
      path: '/auth/accept-invitation'
      fullPath: '/auth/accept-invitation'
      preLoaderRoute: typeof AuthAuthAcceptInvitationRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/forgot-password': {
      id: '/_auth/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthAuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/login': {
      id: '/_auth/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/auth/reset-password': {
      id: '/_auth/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthAuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/fx-rates': {
      id: '/api/cron/fx-rates'
      path: '/api/cron/fx-rates'
      fullPath: '/api/cron/fx-rates'
      preLoaderRoute: typeof ApiCronFxRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-layout/invoices/$id/edit': {
      id: '/_auth-layout/invoices/$id/edit'
      path: '/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof AuthLayoutInvoicesIdEditRouteImport
      parentRoute: typeof AuthLayoutInvoicesIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAuthAcceptInvitationRoute: typeof AuthAuthAcceptInvitationRoute
  AuthAuthForgotPasswordRoute: typeof AuthAuthForgotPasswordRoute
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthResetPasswordRoute: typeof AuthAuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAuthAcceptInvitationRoute: AuthAuthAcceptInvitationRoute,
  AuthAuthForgotPasswordRoute: AuthAuthForgotPasswordRoute,
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthResetPasswordRoute: AuthAuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthLayoutInvoicesIdRouteChildren {
  AuthLayoutInvoicesIdEditRoute: typeof AuthLayoutInvoicesIdEditRoute
}

const AuthLayoutInvoicesIdRouteChildren: AuthLayoutInvoicesIdRouteChildren = {
  AuthLayoutInvoicesIdEditRoute: AuthLayoutInvoicesIdEditRoute,
}

const AuthLayoutInvoicesIdRouteWithChildren =
  AuthLayoutInvoicesIdRoute._addFileChildren(AuthLayoutInvoicesIdRouteChildren)

interface AuthLayoutRouteChildren {
  AuthLayoutActivityRoute: typeof AuthLayoutActivityRoute
  AuthLayoutDashboardRoute: typeof AuthLayoutDashboardRoute
  AuthLayoutSettingRoute: typeof AuthLayoutSettingRoute
  AuthLayoutTeamRoute: typeof AuthLayoutTeamRoute
  AuthLayoutInvoicesIdRoute: typeof AuthLayoutInvoicesIdRouteWithChildren
  AuthLayoutInvoicesNewRoute: typeof AuthLayoutInvoicesNewRoute
  AuthLayoutSettingsBanksRoute: typeof AuthLayoutSettingsBanksRoute
  AuthLayoutSettingsBusinessesRoute: typeof AuthLayoutSettingsBusinessesRoute
  AuthLayoutSettingsCompaniesRoute: typeof AuthLayoutSettingsCompaniesRoute
  AuthLayoutSettingsFxRatesRoute: typeof AuthLayoutSettingsFxRatesRoute
  AuthLayoutSettingsOrganizationRoute: typeof AuthLayoutSettingsOrganizationRoute
  AuthLayoutSettingsProfileRoute: typeof AuthLayoutSettingsProfileRoute
  AuthLayoutClientsIndexRoute: typeof AuthLayoutClientsIndexRoute
  AuthLayoutInvoicesIndexRoute: typeof AuthLayoutInvoicesIndexRoute
  AuthLayoutMemosIndexRoute: typeof AuthLayoutMemosIndexRoute
  AuthLayoutProductsIndexRoute: typeof AuthLayoutProductsIndexRoute
  AuthLayoutSettingsIndexRoute: typeof AuthLayoutSettingsIndexRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthLayoutActivityRoute: AuthLayoutActivityRoute,
  AuthLayoutDashboardRoute: AuthLayoutDashboardRoute,
  AuthLayoutSettingRoute: AuthLayoutSettingRoute,
  AuthLayoutTeamRoute: AuthLayoutTeamRoute,
  AuthLayoutInvoicesIdRoute: AuthLayoutInvoicesIdRouteWithChildren,
  AuthLayoutInvoicesNewRoute: AuthLayoutInvoicesNewRoute,
  AuthLayoutSettingsBanksRoute: AuthLayoutSettingsBanksRoute,
  AuthLayoutSettingsBusinessesRoute: AuthLayoutSettingsBusinessesRoute,
  AuthLayoutSettingsCompaniesRoute: AuthLayoutSettingsCompaniesRoute,
  AuthLayoutSettingsFxRatesRoute: AuthLayoutSettingsFxRatesRoute,
  AuthLayoutSettingsOrganizationRoute: AuthLayoutSettingsOrganizationRoute,
  AuthLayoutSettingsProfileRoute: AuthLayoutSettingsProfileRoute,
  AuthLayoutClientsIndexRoute: AuthLayoutClientsIndexRoute,
  AuthLayoutInvoicesIndexRoute: AuthLayoutInvoicesIndexRoute,
  AuthLayoutMemosIndexRoute: AuthLayoutMemosIndexRoute,
  AuthLayoutProductsIndexRoute: AuthLayoutProductsIndexRoute,
  AuthLayoutSettingsIndexRoute: AuthLayoutSettingsIndexRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronFxRatesRoute: ApiCronFxRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
