/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SettingRouteImport } from './routes/setting'
import { Route as TeamRouteImport } from './routes/team'
import { Route as AuthAcceptInvitationRouteImport } from './routes/auth/accept-invitation'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as MemosIndexRouteImport } from './routes/memos/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsBanksRouteImport } from './routes/settings/banks'
import { Route as SettingsBusinessesRouteImport } from './routes/settings/businesses'
import { Route as SettingsCompaniesRouteImport } from './routes/settings/companies'
import { Route as SettingsFxRatesRouteImport } from './routes/settings/fx-rates'
import { Route as SettingsOrganizationRouteImport } from './routes/settings/organization'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiCronFxRatesRouteImport } from './routes/api/cron/fx-rates'
import { Route as InvoicesIdEditRouteImport } from './routes/invoices/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingRoute = SettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAcceptInvitationRoute = AuthAcceptInvitationRouteImport.update({
  id: '/auth/accept-invitation',
  path: '/auth/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MemosIndexRoute = MemosIndexRouteImport.update({
  id: '/memos/',
  path: '/memos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBanksRoute = SettingsBanksRouteImport.update({
  id: '/settings/banks',
  path: '/settings/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBusinessesRoute = SettingsBusinessesRouteImport.update({
  id: '/settings/businesses',
  path: '/settings/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompaniesRoute = SettingsCompaniesRouteImport.update({
  id: '/settings/companies',
  path: '/settings/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsFxRatesRoute = SettingsFxRatesRouteImport.update({
  id: '/settings/fx-rates',
  path: '/settings/fx-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronFxRatesRoute = ApiCronFxRatesRouteImport.update({
  id: '/api/cron/fx-rates',
  path: '/api/cron/fx-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdEditRoute = InvoicesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => InvoicesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/setting': typeof SettingRoute
  '/team': typeof TeamRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/settings/banks': typeof SettingsBanksRoute
  '/settings/businesses': typeof SettingsBusinessesRoute
  '/settings/companies': typeof SettingsCompaniesRoute
  '/settings/fx-rates': typeof SettingsFxRatesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/clients/': typeof ClientsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/memos/': typeof MemosIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/fx-rates': typeof ApiCronFxRatesRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/setting': typeof SettingRoute
  '/team': typeof TeamRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/settings/banks': typeof SettingsBanksRoute
  '/settings/businesses': typeof SettingsBusinessesRoute
  '/settings/companies': typeof SettingsCompaniesRoute
  '/settings/fx-rates': typeof SettingsFxRatesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/clients': typeof ClientsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/memos': typeof MemosIndexRoute
  '/products': typeof ProductsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/fx-rates': typeof ApiCronFxRatesRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/dashboard': typeof DashboardRoute
  '/setting': typeof SettingRoute
  '/team': typeof TeamRoute
  '/auth/accept-invitation': typeof AuthAcceptInvitationRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/settings/banks': typeof SettingsBanksRoute
  '/settings/businesses': typeof SettingsBusinessesRoute
  '/settings/companies': typeof SettingsCompaniesRoute
  '/settings/fx-rates': typeof SettingsFxRatesRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/clients/': typeof ClientsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/memos/': typeof MemosIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/fx-rates': typeof ApiCronFxRatesRoute
  '/invoices/$id/edit': typeof InvoicesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/setting'
    | '/team'
    | '/auth/accept-invitation'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/invoices/$id'
    | '/invoices/new'
    | '/settings/banks'
    | '/settings/businesses'
    | '/settings/companies'
    | '/settings/fx-rates'
    | '/settings/organization'
    | '/settings/profile'
    | '/clients/'
    | '/invoices/'
    | '/memos/'
    | '/products/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/cron/fx-rates'
    | '/invoices/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/dashboard'
    | '/setting'
    | '/team'
    | '/auth/accept-invitation'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/invoices/$id'
    | '/invoices/new'
    | '/settings/banks'
    | '/settings/businesses'
    | '/settings/companies'
    | '/settings/fx-rates'
    | '/settings/organization'
    | '/settings/profile'
    | '/clients'
    | '/invoices'
    | '/memos'
    | '/products'
    | '/settings'
    | '/api/auth/$'
    | '/api/cron/fx-rates'
    | '/invoices/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/dashboard'
    | '/setting'
    | '/team'
    | '/auth/accept-invitation'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/invoices/$id'
    | '/invoices/new'
    | '/settings/banks'
    | '/settings/businesses'
    | '/settings/companies'
    | '/settings/fx-rates'
    | '/settings/organization'
    | '/settings/profile'
    | '/clients/'
    | '/invoices/'
    | '/memos/'
    | '/products/'
    | '/settings/'
    | '/api/auth/$'
    | '/api/cron/fx-rates'
    | '/invoices/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DashboardRoute: typeof DashboardRoute
  SettingRoute: typeof SettingRoute
  TeamRoute: typeof TeamRoute
  AuthAcceptInvitationRoute: typeof AuthAcceptInvitationRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  InvoicesIdRoute: typeof InvoicesIdRouteWithChildren
  InvoicesNewRoute: typeof InvoicesNewRoute
  SettingsBanksRoute: typeof SettingsBanksRoute
  SettingsBusinessesRoute: typeof SettingsBusinessesRoute
  SettingsCompaniesRoute: typeof SettingsCompaniesRoute
  SettingsFxRatesRoute: typeof SettingsFxRatesRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  MemosIndexRoute: typeof MemosIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronFxRatesRoute: typeof ApiCronFxRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting': {
      id: '/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof SettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/accept-invitation': {
      id: '/auth/accept-invitation'
      path: '/auth/accept-invitation'
      fullPath: '/auth/accept-invitation'
      preLoaderRoute: typeof AuthAcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memos/': {
      id: '/memos/'
      path: '/memos'
      fullPath: '/memos/'
      preLoaderRoute: typeof MemosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/banks': {
      id: '/settings/banks'
      path: '/settings/banks'
      fullPath: '/settings/banks'
      preLoaderRoute: typeof SettingsBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/businesses': {
      id: '/settings/businesses'
      path: '/settings/businesses'
      fullPath: '/settings/businesses'
      preLoaderRoute: typeof SettingsBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/companies': {
      id: '/settings/companies'
      path: '/settings/companies'
      fullPath: '/settings/companies'
      preLoaderRoute: typeof SettingsCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/fx-rates': {
      id: '/settings/fx-rates'
      path: '/settings/fx-rates'
      fullPath: '/settings/fx-rates'
      preLoaderRoute: typeof SettingsFxRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/fx-rates': {
      id: '/api/cron/fx-rates'
      path: '/api/cron/fx-rates'
      fullPath: '/api/cron/fx-rates'
      preLoaderRoute: typeof ApiCronFxRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id/edit': {
      id: '/invoices/$id/edit'
      path: '/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof InvoicesIdEditRouteImport
      parentRoute: typeof InvoicesIdRoute
    }
  }
}

interface InvoicesIdRouteChildren {
  InvoicesIdEditRoute: typeof InvoicesIdEditRoute
}

const InvoicesIdRouteChildren: InvoicesIdRouteChildren = {
  InvoicesIdEditRoute: InvoicesIdEditRoute,
}

const InvoicesIdRouteWithChildren = InvoicesIdRoute._addFileChildren(
  InvoicesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DashboardRoute: DashboardRoute,
  SettingRoute: SettingRoute,
  TeamRoute: TeamRoute,
  AuthAcceptInvitationRoute: AuthAcceptInvitationRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  InvoicesIdRoute: InvoicesIdRouteWithChildren,
  InvoicesNewRoute: InvoicesNewRoute,
  SettingsBanksRoute: SettingsBanksRoute,
  SettingsBusinessesRoute: SettingsBusinessesRoute,
  SettingsCompaniesRoute: SettingsCompaniesRoute,
  SettingsFxRatesRoute: SettingsFxRatesRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  MemosIndexRoute: MemosIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronFxRatesRoute: ApiCronFxRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
